Upgrade core to 2.26.0
A build with 2.0.0 from the core is no longer possible,
because this raises the following error:

/home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/node_modules/to-no-case/index.js:28
  return string.toLowerCase()
                ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at toNoCase (/home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/node_modules/to-no-case/inde
x.js:28:17)
    at toSpaceCase (/home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/node_modules/to-space-cas
e/index.js:18:10)
    at toCamelCase (/home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/node_modules/to-camel-cas
e/index.js:18:10)                                                                                                                                                 at /home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/lib/build-stylesheets-refractor.js:37:
57                                                                                                                                                                at Array.map (<anonymous>)
    at updateDocs (/home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/lib/build-stylesheets-refr
actor.js:37:38)
    at /home/rene/.cache/yarn/v4/.tmp/b8090b644506099e9df6f5ccee5afe2a.08bcf49b1aa7877ce94f7208e73dfa6bef8b26e7.prepare/lib/build-stylesheets-refractor.js:20: